spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - profile
              - email
              - openid
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/test
    h2:
      console:
        enabled: true
    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          default_batch_fetch_size: 100
          format_sql: true
      show-sql: true
    output:
      ansi:
        enabled: always

  logging:
    file:
      name: logs
    level:
      root: DEBUG
app:
  auth:
    token:
      secret-key: ${SECRET_KEY}
