spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - profile
              - email
              - openid
app:
  auth:
    token:
      secret-key: ${SECRET_KEY}
