## 배포환경 기본 세팅
server:
  port: 5000
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  config:
    activate:
      on-profile: prod # 프로파일 설정

#  datasource:
#    url: jdbc:mariadb://${rds.hostname}:${rds.port}/${rds.db.name}
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: ${rds.username}
#    password: ${rds.password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
logging:
  level:
    root: INFO
