### swagger configuration
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  api-docs:
    groups:
      enabled: true

### encoding
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
### default profile
spring:
  profiles:
    default: test
