spring:
  datasource:
    username: sa
    password:
    h2:
      console:
        enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    show-sql: true
  output:
    ansi:
      enabled: always

  logging:
    file:
      name: logs
    level:
      root: DEBUG
#app:
#  auth:
#    token:
#      secret-key: ${SECRET_KEY}
