### swagger configuration
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  api-docs:
    groups:
      enabled: true

### encoding
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
### default profile
spring:
  profiles:
    default: test
#  redis:
#    host: localhost
#    port: 6379
#  mail:
#    host: smtp.naver.com # TODO : google smtp로 구현하기
#    port: 465
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
#            trust: smtp.naver.com
