## 배포환경 기본 세팅
server:
  port: 5000
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  config:
    activate:
      on-profile: prod # 프로파일 설정

  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    database: mysql # update
logging:
  level:
    root: INFO
