spring:
  profiles:
    include: test
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google

#            token-uri: https://oauth2.googleapis.com/token
#            resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

#            scope:
#              - profile
#              - email
#              - openid


# swagger configuration
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  api-docs:
    groups:
      enabled: true

# OIDC testing...
#logging:
#  level:
#    org.springframework.web.client.RestTemplate: DEBUG
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

