#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${CLIENT_ID}
#            client-secret: ${CLIENT_SECRET}
#            redirect-uri: http://localhost:8080/login/oauth2/code/google
#            scope:
#              - profile
#              - email
#              - openid

### swagger configuration
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  api-docs:
    groups:
      enabled: true

### encoding
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

